### ISSUE TITLE
PITclipse not working if launched from source code

### ISSUE THREAD

**Issue by JKutscha** [pitest/pitclipse#137]
## Bug description

When PITclipse gets launched from the source code it does not work.

I'm not sure if this is the right place to write this, if not please point to the right place.

## Expected behavior

Launch PITclipse and see an working result.

## How to reproduce

1. Followed instructions to clone code
2. Launch Eclipse Application
3. Start PITClipse for test class

## Additional context

Eclipse Version: 2021-06 (4.20.0)

Stack trace from development Eclipse:
org.pitest.pitclipse.runner.io.ObjectStreamSocket$ReadException: java.io.EOFException
	at org.pitest.pitclipse.runner.io.ObjectStreamSocket.read(ObjectStreamSocket.java:82)
	at org.pitest.pitclipse.runner.server.PitServer.receiveResults(PitServer.java:102)
	at org.pitest.pitclipse.runner.client.PitCommunicator.run(PitCommunicator.java:61)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.EOFException
	at java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:3078)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1618)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:503)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:461)
	at org.pitest.pitclipse.runner.io.ObjectStreamSocket.read(ObjectStreamSocket.java:80)
	... 5 more
Exception in thread "pool-1-thread-1" org.pitest.pitclipse.runner.io.ObjectStreamSocket$ReadException: java.io.EOFException
	at org.pitest.pitclipse.runner.io.ObjectStreamSocket.read(ObjectStreamSocket.java:82)
	at org.pitest.pitclipse.runner.server.PitServer.receiveResults(PitServer.java:102)
	at org.pitest.pitclipse.runner.client.PitCommunicator.run(PitCommunicator.java:61)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.EOFException
	at java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:3078)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1618)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:503)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:461)
	at org.pitest.pitclipse.runner.io.ObjectStreamSocket.read(ObjectStreamSocket.java:80)
	... 5 more

Output from started Eclipse:
15:52:04 PIT >> INFO : ---------------------------------------------------------------------------
15:52:04 PIT >> INFO : Enabled (+) and disabled (-) features.
15:52:04 PIT >> INFO : -----------------------------------------
15:52:04 PIT >> INFO : +FANN           Filters mutations in classes and methods with matching annotations of class or runtime retention
15:52:04 PIT >> INFO :   [annotation]    Annotation to avoid (full package name not required)
15:52:04 PIT >> INFO : +FFBLOCK        Filters mutations in code duplicated by finally block inlining
15:52:04 PIT >> INFO : +FFEACH         Filters mutations in compiler generated code that implements for each loops
15:52:04 PIT >> INFO : +FFLOOP         Filters any mutations to increments in for loops as they may cause timeouts
15:52:04 PIT >> INFO : +FINFINC        Filters mutations to increments that may cause infinite loops
15:52:04 PIT >> INFO : +FINFIT         Filters mutations that may cause infinite loops by removing calls to iterator.next
15:52:04 PIT >> INFO : +FINULL         Filters mutations in compiler generated code that checks for null by calling getClass
15:52:04 PIT >> INFO : +FKOTLIN        Filters out junk mutations in bytecode created by compiler for kotlin language features
15:52:04 PIT >> INFO : +FLOGCALL       Filters mutations in code that makes calls to logging frameworks
15:52:04 PIT >> INFO : +FMRNULL        Filters mutations in compiler generated code that inserts Objects.requireNonNull for method references
15:52:04 PIT >> INFO : +FRETEQUIV      Filters return vals mutants with bytecode equivalent to the unmutated class
15:52:04 PIT >> INFO : +FSEQUIVEQUALS  Filters equivalent mutations that affect only performance in short cutting equals methods
15:52:04 PIT >> INFO : +FSTATI         Filters mutations in static initializers and code called only from them
15:52:04 PIT >> INFO : +FSTATINIT      Filters mutations in static initializers and code called only from them
15:52:04 PIT >> INFO : +FTRYWR         Filters mutations in code generated for try with resources statements
15:52:04 PIT >> INFO : -CLASSLIMIT     Limits the maximum number of mutations per class
15:52:04 PIT >> INFO :   [limit]         Integer value for maximum mutations to create per class
15:52:04 PIT >> INFO : -EXPORT         Exports mutants bytecode and other details to disk
15:52:04 PIT >> INFO : ---------------------------------------------------------------------------
Exception in thread "main" org.pitest.util.PitError: Unknown listener requested in HTML,PITCLIPSE_MUTATIONS,PITCLIPSE_SUMMARY

Please copy and paste the information and the complete stacktrace below when reporting an issue
VM : OpenJDK 64-Bit Server VM
Vendor : Oracle Corporation
Version : 25.292-b10
Uptime : 546
Input -> 
 1 : -Dfile.encoding=Cp1252
BootClassPathSupported : true

	at org.pitest.mutationtest.config.SettingsFactory.findListeners(SettingsFactory.java:144)
	at org.pitest.mutationtest.config.SettingsFactory.createListener(SettingsFactory.java:71)
	at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:95)
	at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:50)
	at org.pitest.mutationtest.commandline.MutationCoverageReport.runReport(MutationCoverageReport.java:87)
	at org.pitest.mutationtest.commandline.MutationCoverageReport.main(MutationCoverageReport.java:45)
	at org.pitest.pitclipse.runner.PitRunner.lambda$1(PitRunner.java:59)
	at com.google.common.base.Present.transform(Present.java:75)
	at org.pitest.pitclipse.runner.PitRunner.main(PitRunner.java:46)

**Comment by JKutscha** [comment]
Today I did everything the same on my Linux pc and it works fine. Maybe it is an Issue with Windows 10?!
