### ISSUE TITLE
Error al correr test

### ISSUE THREAD

**Issue by dfloresg** [pitest/pitclipse#220]
## Bug description

Al momento de correr un proyecto maven al terminar en consola se presenta el siguiente error:

Exception in thread "main" org.pitest.help.PitHelpError: 4 tests did not pass without mutation when calculating line coverage. Mutation testing requires a green suite.
See http://pitest.org for more details.
	at org.pitest.coverage.execute.DefaultCoverageGenerator.verifyBuildSuitableForMutationTesting(DefaultCoverageGenerator.java:115)
	at org.pitest.coverage.execute.DefaultCoverageGenerator.calculateCoverage(DefaultCoverageGenerator.java:97)
	at org.pitest.coverage.execute.DefaultCoverageGenerator.calculateCoverage(DefaultCoverageGenerator.java:52)
	at org.pitest.mutationtest.tooling.MutationCoverage.runAnalysis(MutationCoverage.java:149)
	at org.pitest.mutationtest.tooling.MutationCoverage.runReport(MutationCoverage.java:139)
	at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:125)
	at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:52)
	at org.pitest.mutationtest.commandline.MutationCoverageReport.runReport(MutationCoverageReport.java:98)
	at org.pitest.mutationtest.commandline.MutationCoverageReport.main(MutationCoverageReport.java:45)
	at org.pitest.pitclipse.runner.PitRunner.apply(PitRunner.java:35)
	at org.pitest.pitclipse.runner.PitRunner.apply(PitRunner.java:1)
	at java.base/java.util.Optional.map(Optional.java:265)
	at org.pitest.pitclipse.runner.PitRunnerMain.main(PitRunnerMain.java:38)

Adicional a estoy en el tab PIT Mutations no se presenta nada

## Expected behavior

Es la primera vez que lo uso y no tuve una buena experiencia

## How to reproduce

1. Dar clic derecho en el proyecto
2. Click on Run As.. y luego en PIT Mutation Test

## Additional context

- Pitclipse 2.2.0
-Spring Tool Suite 4 (Version: 4.14.1.RELEASE
Build Id: 202204250734) 
![Captura desde 2023-04-28 16-27-33](https://user-images.githubusercontent.com/108107085/235257191-ee1e50bb-55f4-4d8b-afce-7841c841ded0.png)

**Comment by LorenzoBettini** [comment]
Please, write issues in English.

The message says "Mutation testing requires a green suite.", so, before running mutation testing, you must make sure that your tests are green.

You're also using old versions of pitclipse (and spring).

Without additional information, I'd close this issue.
